spring.application.name=DescriptionCreator
server.port=${SERVER_PORT:8080}

shopify.shop-domain=${SHOPIFY_SHOP_DOMAIN:}
shopify.access-token=${SHOPIFY_ACCESS_TOKEN:}
shopify.api-version=${SHOPIFY_API_VERSION:2026-07}
